@baseUrl = http://localhost:8080
@neoClientId = "318e2e9f-29c9-4c25-9679-0056131f5ad9"
@morpheusClientId = "d084626b-7288-456e-b7ce-c36c7c4d642c"

### -------------------------------------------------------
### 1. HEALTH CHECK
### -------------------------------------------------------
GET {{baseUrl}}/health

### -------------------------------------------------------
### 2. CLIENTES
### -------------------------------------------------------

### Listar todos os clientes
GET {{baseUrl}}/clients

### Criar Cliente 1 (Neo)
# @name createNeo
POST {{baseUrl}}/clients
Content-Type: application/json

{
    "name": "Neo",
    "email": "neo@matrix.com"
}

### Criar Cliente 2 (Morpheus)
# @name createMorpheus
POST {{baseUrl}}/clients
Content-Type: application/json

{
    "name": "Morpheus",
    "email": "morpheus@matrix.com"
}

### -------------------------------------------------------
### 3. CONTAS
### -------------------------------------------------------

### Listar todas as contas
GET {{baseUrl}}/accounts

### Criar Conta Neo
# Copie o ID do Neo da resposta acima e cole abaixo
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "client_id": {{neoClientId}}
}

@neoAccountId = f0927c23-ded7-4024-8957-b2decd701987

### Criar Conta Morpheus
# Copie o ID do Morpheus da resposta acima e cole abaixo
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "client_id": {{morpheusClientId}}
}

@MorpheusAccountId = 7a60e39c-b601-412d-b1e4-af65fcebde9e

### Ver Saldo (Conta Neo)
GET {{baseUrl}}/accounts/{{neoAccountId}}/balance


### Ver Saldo (Conta Morpheus)
GET {{baseUrl}}/accounts/{{MorpheusAccountId}}/balance

### Creditar Saldo (Teste)
POST {{baseUrl}}/accounts/{{neoAccountId}}/credit
Content-Type: application/json

{
    "amount": 1000
}

### -------------------------------------------------------
### 4. TRANSAÇÕES
### -------------------------------------------------------

### Realizar Transferência (Neo -> Morpheus)
# Lembre-se: Neo precisa ter saldo (credite via REPL se precisar)
POST {{baseUrl}}/transactions
Content-Type: application/json

{
    "account_id_from": "{{neoAccountId}}",
    "account_id_to": "{{MorpheusAccountId}}",
    "amount": 100
}

### -------------------------------------------------------
### 5. RELATÓRIOS
### -------------------------------------------------------

### Extrato (Statement) - Histórico da Conta
GET {{baseUrl}}/accounts/{{neoAccountId}}/transactions


### -------------------------------------------------------
### 6. BALANCES SERVICE (NOVO)
### -------------------------------------------------------
@balanceUrl = http://localhost:3003

### Consultar Saldo no Microsserviço de Balances (Neo)
GET {{balanceUrl}}/balances/{{neoAccountId}}

### Consultar Saldo no Microsserviço de Balances (Morpheus)
GET {{balanceUrl}}/balances/{{MorpheusAccountId}}
